STOCKS = [
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK", "HINDUNILVR", "SBIN", "BHARTIARTL", "KOTAKBANK", "ITC",
    "BAJFINANCE", "ASIANPAINT", "WIPRO", "HCLTECH", "AXISBANK", "MARUTI", "SUNPHARMA", "TATAMOTORS", "TITAN", "ULTRACEMCO",
    "NESTLEIND", "LT", "M&M", "INDUSINDBK", "POWERGRID", "NTPC", "ONGC", "TATASTEEL", "JSWSTEEL", "ADANIENT",
    "ADANIPORTS", "COALINDIA", "BPCL", "HEROMOTOCO", "DIVISLAB", "DRREDDY", "GRASIM", "CIPLA", "BAJAJ-AUTO", "EICHERMOT",
    "BRITANNIA", "SHREECEM", "TECHM", "PIDILITIND", "DABUR", "HDFCLIFE", "SBILIFE", "IOC", "APOLLOHOSP", "MARICO",
    "ADANIGREEN", "GAIL", "DLF", "ICICIPRULI", "HAVELLS", "TATACONSUM", "SIEMENS", "GODREJCP", "MUTHOOTFIN", "LTI",
    "BERGEPAINT", "NAUKRI", "BANDHANBNK", "INDIGO", "BIOCON", "AUROPHARMA", "ACC", "AMBUJACEM", "ADANITRANS", "UPL",
    "TORNTPHARM", "VEDL", "MANAPPURAM", "BOSCHLTD", "PAGEIND", "PEL", "SRF", "LUPIN", "ZOMATO", "MPHASIS", "TRENT",
    "ADANIPOWER", "HINDZINC", "CHOLAFIN", "JINDALSTEL", "MCDOWELL-N", "PIIND", "BANKBARODA", "CANBK", "GLAND", "POLICYBZR",
    "IRCTC", "TVSMOTOR", "IDFCFIRSTB", "COFORGE", "NMDC", "MGL", "IGL", "BEL", "HAL", "BHEL", "CONCOR", "DELHIVERY",
    "PATANJALI", "NYKAA", "AUBANK", "INDHOTEL", "ABB", "PERSISTENT", "ASTRAL", "CROMPTON", "HINDPETRO", "SUMICHEM",
    "ICICIGI", "ALKEM", "TATAPOWER", "SYNGENE", "GODREJPROP", "SUNDARMFIN", "ESCORTS", "WHIRLPOOL", "OBEROIRLTY",
    "IDFC", "LICI", "NAVINFLUOR", "BALKRISIND", "COROMANDEL", "PNB", "DEEPAKNTR", "JSWENERGY", "LAURUSLABS", "RAMCOCEM",
    "ABBOTINDIA", "BALRAMCHIN", "CANFINHOME", "GLAXO", "INDIAMART", "IPCALAB", "JUBLFOOD", "KAJARIACER", "LALPATHLAB",
    "MFSL", "MOTILALOFS", "PFIZER", "RECLTD", "TATACHEM", "THERMAX", "VOLTAS", "WHIRLPOOL", "ZEEL", "ZYDUSLIFE"
]


MARKET_CAP_CATEGORIES = {
    "🏆 Large Cap Champions": [
        "RELIANCE", "TCS", "HDFCBANK", "INFY", "HINDUNILVR", "ITC", "ICICIBANK", "KOTAKBANK", "SBIN", "BHARTIARTL",
        "ASIANPAINT", "HCLTECH", "MARUTI", "AXISBANK", "LT", "BAJFINANCE", "SUNPHARMA", "TITAN", "ULTRACEMCO",
        "NESTLEIND", "WIPRO", "M&M", "POWERGRID", "NTPC", "ONGC", "TATASTEEL", "JSWSTEEL", "ADANIENT", "ADANIPORTS",
        "COALINDIA", "BPCL", "HEROMOTOCO", "DIVISLAB", "DRREDDY", "GRASIM", "CIPLA", "BAJAJ-AUTO", "EICHERMOT",
        "BRITANNIA", "SHREECEM", "TECHM", "PIDILITIND", "DABUR", "HDFCLIFE", "SBILIFE", "IOC", "APOLLOHOSP", "MARICO",
        "ADANIGREEN", "GAIL", "DLF", "ICICIPRULI", "HAVELLS", "TATACONSUM", "SIEMENS", "GODREJCP", "MUTHOOTFIN",
        "BERGEPAINT", "NAUKRI", "BANDHANBNK", "INDIGO", "BIOCON", "AUROPHARMA", "ACC", "AMBUJACEM", "ADANITRANS",
        "UPL", "TORNTPHARM", "VEDL", "MANAPPURAM", "BOSCHLTD", "PAGEIND", "PEL", "SRF", "LUPIN", "ZOMATO", "MPHASIS",
        "TRENT", "ADANIPOWER", "HINDZINC", "CHOLAFIN", "JINDALSTEL", "PIIND", "BANKBARODA", "CANBK", "GLAND", "POLICYBZR",
        "IRCTC", "TVSMOTOR", "COFORGE", "NMDC", "MGL", "IGL", "BEL", "HAL", "BHEL", "CONCOR", "DELHIVERY", "PATANJALI",
        "NYKAA", "AUBANK", "INDHOTEL", "ABB", "PERSISTENT", "ASTRAL", "CROMPTON", "HINDPETRO", "SUMICHEM", "ICICIGI",
        "ALKEM", "TATAPOWER", "SYNGENE", "GODREJPROP", "SUNDARMFIN", "ESCORTS", "WHIRLPOOL", "OBEROIRLTY", "IDFC",
        "LICI", "NAVINFLUOR", "BALKRISIND", "COROMANDEL", "PNB", "DEEPAKNTR", "JSWENERGY", "LAURUSLABS", "RAMCOCEM",
        "ABBOTINDIA", "BALRAMCHIN", "CANFINHOME", "GLAXO", "INDIAMART", "IPCALAB", "JUBLFOOD", "KAJARIACER", "LALPATHLAB",
        "MFSL", "MOTILALOFS", "PFIZER", "RECLTD", "TATACHEM", "THERMAX", "VOLTAS", "ZEEL", "ZYDUSLIFE"
    ],
    "💎 Mid Cap Gems": [
        "CUMMINSIND", "COLPAL", "LUPIN", "INDHOTEL", "MAXHEALTH", "DIXON", "PERSISTENT", "POLICYBZR", "SUZLON",
        "PIIND", "LTIM", "AUROPHARMA", "ABB", "BOSCHLTD", "SRF", "TRENT", "CHOLAFIN", "CANBK", "MUTHOOTFIN",
        "PAGEIND", "ICICIPRULI", "HAVELLS", "MFSL", "PEL", "ICICIGI", "GLAND", "TATASTEEL", "OBEROIRLTY", "ZOMATO",
        "POLYCAB", "TORNTPHARM", "NAUKRI", "BANDHANBNK", "HINDPETRO", "MARICO", "AUBANK", "MPHASIS", "TVSMOTOR",
        "MANYAVAR", "CONCOR", "BERGEPAINT", "DLF", "MGL", "IOC", "VBL", "TATAPOWER", "IPCALAB", "ALKEM", "BHARATFORG",
        "SUNTV", "GODREJCP", "LICHSGFIN", "BANKBARODA", "BATAINDIA", "APOLLOHOSP", "INDIGO", "JUBLFOOD", "ADANIGREEN",
        "ADANIPORTS", "ADANITRANS", "DIVISLAB", "GRASIM", "JSWSTEEL", "BPCL", "HDFCLIFE", "TECHM", "COALINDIA",
        "HEROMOTOCO", "BRITANNIA", "CIPLA", "SHREECEM", "DABUR", "DRREDDY", "EICHERMOT", "TATACONSUM", "VEDL", "GAIL",
        "HINDALCO", "UPL", "SIEMENS"
    ],
    "🚀 Small Cap Stars": [
        "PERSISTENT", "RVNL", "SUZLON", "BSE", "COFORGE", "RAYMOND", "RADICO", "RBLBANK", "REDINGTON", "RAILTEL",
        "RITES", "RKFORGE", "LAURUSLABS", "KAYNES", "UCOBANK", "CENTRALBK", "GLENMARK", "360ONE", "BLUESTARCO",
        "NAVINFLUOR", "CYIENT", "GAIL", "WHIRLPOOL", "JINDALSTEL", "PRAJIND", "BANKBARODA", "KALYANKJIL", "GRSE",
        "KARURVYSYA", "JYOTHYLAB", "SOBHA", "ASTERDM", "CREDITACC", "JINDALSAW", "EIDPARRY", "MMTC", "BALRAMCHIN",
        "JSL", "MAHLOG", "TATAELXSI", "FSL", "HEG", "GRAPHITE", "HFCL", "IRCON", "IRFC", "NHPC", "NLCINDIA", "NBCC",
        "HUDCO", "SCI", "RVNL", "IRCTC", "BEL", "BEML", "BDL", "HAL", "GRSE", "MAZDOCK", "COCHINSHIP", "GSL",
        "HINDCOPPER", "MOIL", "NFL", "RCF", "FACT", "GSFC", "GNFC", "MRPL", "OIL", "IGL", "ONGC", "HINDPETRO", "BPCL",
        "IOC", "GICRE", "NIACL", "RECLTD", "PFC", "SJVN", "NTPC"
    ]
}

BUSINESS_CATEGORIES = {
    "🏭 Ambani Empire": [
        "RELIANCE", "JIOFIN"
    ],
    "🏢 Adani Universe": [
        "ADANIENT", "ADANIPORTS", "ADANIPOWER", "ADANIGREEN", "ADANITRANS",
        "ATGL"
    ],
    "💰 Banking Titans": [
        "HDFCBANK", "ICICIBANK", "SBIN", "KOTAKBANK", "AXISBANK",
        "BANKBARODA", "INDUSINDBK", "AUBANK", "BANDHANBNK", "CANBK"
    ],
    "💻 Tech Warriors": [
        "TCS", "INFY", "WIPRO", "HCLTECH", "TECHM", "LTIM",
        "PERSISTENT", "COFORGE", "MPHASIS", "NAUKRI"
    ],
    "🚗 Auto Legends": [
        "MARUTI", "TATAMOTORS", "M&M", "HEROMOTOCO", "BAJAJ-AUTO",
        "EICHERMOT", "TVSMOTOR", "BHARATFORG"
    ],
    "🏥 Healthcare Heroes": [
        "SUNPHARMA", "CIPLA", "DIVISLAB", "DRREDDY", "APOLLOHOSP",
        "MAXHEALTH", "ALKEM", "LUPIN", "GLAND", "BIOCON"
    ],
    "🛍️ Consumer Kings": [
        "HINDUNILVR", "ITC", "NESTLEIND", "BRITANNIA", "TATACONSUM",
        "DABUR", "MARICO", "COLPAL", "GODREJCP", "VBL"
    ],
    "⚡ Power & Energy": [
        "POWERGRID", "NTPC", "TATAPOWER", "ADANIPOWER", "TORNTPOWER",
        "ONGC", "IOC", "BPCL", "GAIL", "MGL"
    ],
    "🏗️ Infrastructure Giants": [
        "LT", "ULTRACEMCO", "SHREECEM", "GRASIM", "ADANICEM.NS",
        "DLF", "OBEROIRLTY", "CONCOR", "SIEMENS", "ABB"
    ],
    "💎 Metal & Mining": [
        "TATASTEEL", "HINDALCO", "JSWSTEEL", "VEDL", "COALINDIA",
        "JINDALSTEL", "SAIL", "NATIONALUM", "MOIL", "NMDC"
    ],
    "📱 Telecom & Digital": [
        "BHARTIARTL", "IDEA", "TATACOMM", "ZOMATO", "PAYTM",
        "NAUKRI", "POLICYBZR", "IRCTC"
    ],
    "🌟 Tata Universe": [
        "TCS", "TATAMOTORS", "TATASTEEL", "TATAPOWER", "TATACOMM",
        "TATACONSUM", "TATAINVEST", "VOLTAS", "TITAN", "TRENT"
    ],
    "💫 Birla Galaxy": [
        "ULTRACEMCO", "HINDALCO", "GRASIM", "ADITYABIRLA", "ABCAPITAL",
        "IDEA", "ABFRL", "MANYAVAR"
    ],
    "🎯 New Age Leaders": [
        "ZOMATO", "PAYTM", "NAUKRI", "POLICYBZR", "DELHIVERY",
        "NYKAA", "CARTRADE", "PBFINTECH", "EASEMYTRIP"
    ]
}

# Cache settings
CACHE_EXPIRY = 3600  # 1 hour in seconds

# Create a flat list of all stocks for API usage
ALL_STOCKS = list(set(
    [stock for category in MARKET_CAP_CATEGORIES.values() for stock in category] +
    [stock for category in BUSINESS_CATEGORIES.values() for stock in category]
))

# Combined categories for API
STOCK_CATEGORIES = {**MARKET_CAP_CATEGORIES, **BUSINESS_CATEGORIES}

 
